# Generated by Django 3.1.5 on 2021-01-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='wedding',
            new_name='weddingId',
        ),
        migrations.AlterField(
            model_name='photo',
            name='number',
            field=models.IntegerField(),
        ),
    ]
