# Generated by Django 2.1.15 on 2021-01-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='image',
            field=models.CharField(default='https://images.unsplash.com/reserve/xd45Y326SvKzSR3Nanc8_MRJ_8125-1.jpg?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1050&q=80', max_length=255),
        ),
    ]
