# Generated by Django 2.1.15 on 2021-01-05 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_photoguest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Guest')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wedding')),
            ],
        ),
    ]
