# Generated by Django 3.1.5 on 2021-01-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_weddingguest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
